# Site settings
name: stephen appiah
title: steph appiah | backend software engineer
description: software engineer & space enthusiast
url: https://stephappiah.github.io/
baseurl: ''
email: hi@stevenwithph.com
cover: https://stephappiah.github.io/img/og.png
logo: https://stephappiah.github.io/img/emojis/technologist.png
resume: https://stephappiah.github.io/resume.pdf
social:
  - title: email
    url: mailto:hi@stevenwithph.com
  - title: twitter
    url: https://twitter.com/stevenwithph
  - title: github
    url: https://github.com/stephappiah
  # - title: linkedin
  #   url: https://www.linkedin.com/in/stephappiah

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
